version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5052:5052"
    volumes:
      - backend_data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_data: 